Add flakes support
sbruder/vs-overlay pull request #1
Opened 2021-02-22 01:50 UTC by tadeokondrak

This makes it easy to use packages from here when using Nix flakes.
Feel free to close this if you don't/won't use flakes.

2021-05-14 20:07 UTC, sbruder commented
Sorry for leaving this unanswered for so long, GitHub did not make me watch the repository so I did not get a notification about this PR.

2021-05-14 20:10 UTC, sbruder requested changes
This looks nice, thank you! The only missing thing is `getnative` in the `packages` output (see inline comment).

2021-05-14 20:10 UTC, sbruder commented on flake.nix
> +        inherit (nixpkgsFor.${system}) vapoursynthPlugins;
```suggestion
        inherit (nixpkgsFor.${system})
          getnative
          vapoursynthPlugins;
```
`getnative` is currently not accessible via the `packages` output

2021-05-14 20:15 UTC, sbruder commented
On another note, do you want to continue development upstream in your repository or in my fork?

I originally planned to open a PR to your repository but never found the time to test all plugins well enough (and e.g. debanding with placebo still produces strange artifacts that I couldn’t fix).

2021-05-18 04:26 UTC, tadeokondrak commented
> On another note, do you want to continue development upstream in your repository or in my fork?
>
> I originally planned to open a PR to your repository but never found the time to test all plugins well enough (and e.g. debanding with placebo still produces strange artifacts that I couldn’t fix).

I don't use VapourSynth very often, but it would be nice to have a project like this that other people interested in VapourSynth and Nix can contribute to somewhere. It doesn't really matter to me if it's in this repo or mine.

I'll add an MIT license into my repo now. I'd definitely merge this work and make you a committer on the original repo if you'd be fine with that.

2021-05-18 05:20 UTC, sbruder approved these changes
Thanks for addressing my suggestions!

2021-05-18 05:27 UTC, sbruder commented
> I'll add an MIT license into my repo now. I'd definitely merge this work and make you a committer on the original repo if you'd be fine with that.

Of course, thank you!

I’ll merge this later and try to test all plugins I added over the next few days so I can create a PR to your repository.

2021-05-18 16:23 UTC, merged